# customize with: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
alertmanager:
  enabled: true
  baseURL: "https://alertmanager.k8s.gazirahman.dev"
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: htpasswd
      nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"
    hosts:
      - alertmanager.k8s.gazirahman.dev
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.k8s.gazirahman.dev


prometheus:
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: htpasswd
      nginx.ingress.kubernetes.io/auth-realm: "Enter your credentials"
    hosts:
      - prometheus.k8s.gazirahman.dev
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.k8s.gazirahman.dev

  prometheusSpec:
    retention: 14d
    scrapeInterval: 30s
    evaluationInterval: 30s
    externalUrl: "https://prometheus.k8s.gazirahman.dev"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi # you probably want more for production
